FROM node:13.12.0-alpine

ENV  REACT_APP_API_URL=$REACT_APP_API_URL

WORKDIR /wearwatchcare

# add `/wearwatchcare/node_modules/.bin` to $PATH
ENV PATH /wearwatchcare/node_modules/.bin:$PATH

COPY package.json ./

RUN npm install cross-env

RUN npm install --legacy-peer-deps

RUN npm i serve -g

COPY . .

RUN npm run build

CMD ["npm", "prod"]
